version: "3.8"

services:
  billing-app:
    build:
      context: ./billing/flask-in
      dockerfile: Dockerfile
    image: billing-app:1.0
    container_name: billing-app
    working_dir: /app
    env_file: .env
    ports:
      - "5500:5000"
    volumes:
      - ./billing/flask-in:/app
    depends_on:
      - billdb
    networks:
      - backend

  billdb:
    image: mysql:5.7
    container_name: billdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./billing/billdb:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge