version: "3.8"

services:
  billing-app:
    build:
      context: ./billing/flask-in
      dockerfile: Dockerfile
    image: billing-app:1.0
    container_name: billing-app
    working_dir: /app
    env_file: .env
    ports:
      - "5500:5500"
    volumes:
      - billing-files:/app/in     # Input files directory for Excel uploads
    depends_on:
      - billdb
    networks:
      - backend
    restart: unless-stopped

  billdb:
    image: mysql:5.7
    container_name: billdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./billing/billdb:/docker-entrypoint-initdb.d
      - billing-data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped

# Named volumes for persistence
volumes:
  billing-data:    # MySQL database files
  billing-files:   # Input files for processing

networks:
  backend:
    driver: bridge