version: '3.8'

services:
  weight_app:
    build:
      context: ./weight
    container_name: weight-app 
    ports:
      - "8082:5000"
    depends_on:
      weight_db:
       condition: service_healthy
    volumes:
      - ./weight/src:/weight_app
      - ./weight/in:/weight/in
    env_file:
      - ./weight/env
    networks:
      - mynet

  weight_db:
    image: mysql:8
    container_name: weight-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./weight/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql  # Mount the SQL file
      - ./weight/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    networks:
      - mynet

billing-app:
    image: python:3.12-slim
    container_name: billing-app
    working_dir: /app
    volumes:
      - ./billing/flask-in:/app
    command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=billdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=billdb
    ports:
      - "8083:5001"
    depends_on:
      - billdb
    networks:
    - mynet

billdb:
    image: mysql:5.7
    container_name: billdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billdb
    ports:
      -8084:3306
    volumes:
      - ./billing/billdb:/docker-entrypoint-initdb.d
    networks:
      - mynet


networks:
  mynet:
    driver: bridge






