services:
  ci-runner:
    image: docker:28.1.1-cli
    container_name: ci-runner
    privileged: true
    networks:
      - weight-network
      - weight-network_test
    ports:
      - "8080:8080"
    working_dir: /ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/ci                        # CI runner logic
      - ../../test_env:/test_env  # Test repo
      - ../../prod_env:/prod_env  # Production repo
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TEST_HOST=ci-weight_app_test-1
    env_file:
      - .env
    command: >
      sh -c "
      apk add --no-cache python3 py3-pip git &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      python3 webhook.py"
     
networks:
  weight-network:
    external: true
  weight-network_test: