services:
  weight_app_test:
    privileged: true
    build: ../test_env/${BRANCH_NAME}/weight/
    networks:
      - weight-network_test
    ports:
      - "5000:5000"
    depends_on:
      weight_db1_test:
        condition: service_healthy
    environment:
      TEST_HOST: ci-weight_app_test-1
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: weightuser
      MYSQL_PASSWORD: weightpass
      MYSQL_HOST: weight_db1_test  # <-- Changed from weight_db1 to weight_db1_test
    volumes:
      - ${TEST_WEIGHT_PATH_IN}/${BRANCH_NAME}/weight/in:/app/in
  
  weight_db1_test:
    image: mysql:8
    restart: always
    privileged: true
    networks:
      - weight-network_test
    environment:
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: weightuser
      MYSQL_PASSWORD: weightpass
    ports:
      - "3308:3306"
    volumes:
      - ../test_env/${BRANCH_NAME}/weight/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - ../test_env/${BRANCH_NAME}/weight/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s



  billing-app:
    build:
      context: ./billing/flask-in
      dockerfile: Dockerfile
    image: billing-app:1.0
    container_name: billing-app
    working_dir: /app
    environment:
      MYSQL_HOST: billdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456         # ✅ Must match MYSQL_ROOT_PASSWORD from billdb
      MYSQL_DATABASE: billingdb
    ports:
      - "5500:5500"
    volumes:
      - ./billing/flask-in/in:/app/in
    depends_on:
      - billdb
    networks:
      - backend
    restart: unless-stopped

  billdb:
    image: mysql:5.7
    container_name: billdb
    environment:
      MYSQL_ROOT_PASSWORD: 123456    # ✅ Must match billing-app's MYSQL_PASSWORD
      MYSQL_DATABASE: billingdb
    ports:
      - "3306:3306"
    volumes:
      - ./billing/billdb:/docker-entrypoint-initdb.d
      - billing-data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped

  volumes:
    billing-data:
    db_data:


networks:
  backend:
    driver: bridge
    external: true
  weight-network_test:
    external: true
