services:
  ci-runner:
    image: docker:28.1.1-cli
    container_name: ci-runner
    privileged: true
    networks:
      - weight-network
    ports:
      - "8080:8080"
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      sh -c "
      apk add --no-cache python3 py3-pip git &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      echo 'Setup complete. Container is idle.' &&
      tail -f /dev/null"
#python3 webhook.py"
networks:
  weight-network:
    external: true