services:
  weight_app_test:
    privileged: true
    build: ../test_env/${BRANCH_NAME}/weight/
    networks:
      - weight-network_test
    ports:
      - "5000:5000"
    depends_on:
      weight_db1_test:
        condition: service_healthy
    environment:
      TEST_HOST: ci-weight_app_test-1
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: wightuser
      MYSQL_PASSWORD: weightpass
      MYSQL_HOST: weight_db1_test  # <-- Changed from weight_db1 to weight_db1_test
    volumes:
      - ${TEST_WEIGHT_PATH_IN}/${BRANCH_NAME}/weight/in:/app/in
  
  weight_db1_test:
    image: mysql:8
    restart: always
    privileged: true
    networks:
      - weight-network_test
    environment:
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: wightuser
      MYSQL_PASSWORD: weightpass
    ports:
      - "3308:3306"
    volumes:
      - ../test_env/${BRANCH_NAME}/weight/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - ../test_env/${BRANCH_NAME}/weight/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:




# billing-app:
#     image: python:3.12-slim
#     container_name: billing-app
#     working_dir: /app
#     volumes:
#       - ../test_env/billing/flask-in:/app
#     command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_ENV=development
#       - MYSQL_HOST=billdb
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#       - MYSQL_DATABASE=billdb
#     ports:
#       - "5500:5500"
#     depends_on:
#       - billdb
#     networks:
#     - mynet

# billdb:
#     image: mysql:5.7
#     container_name: billdb
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: billdb
#     ports:
#       -3309:3306
#     volumes:
#       - ../test_env/billing/billdb:/docker-entrypoint-initdb.d
#     networks:
#       - mynet

networks:
  weight-network_test:
    external: true
