services:
  ci-runner:
    image: docker:28.1.1-cli
    container_name: ci-runner
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      sh -c "
      apk add --no-cache python3 py3-pip git &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      python3 webhook.py"
 