services:
  weight_app:
    privileged: true
    build: ../../prod_env/main/weight/
    networks:
      - weight-network
    ports:
      - "8082:5000"
    restart: on-failure
    depends_on:
      weight_db1:
        condition: service_healthy
    environment:
      TEST_HOST: ci-weight_app-1
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: wightuser
      MYSQL_PASSWORD: weightpass
      MYSQL_HOST: weight_db1
    volumes:
      - ${WEIGHT_PATH_IN}:/app/in
  
  weight_db1:
    image: mysql:8
    restart: always
    privileged: true
    networks:
      - weight-network
    environment:
      TEST_HOST: ci-weight_app-
      MYSQL_DATABASE: weightdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: wightuser
      MYSQL_PASSWORD: weightpass
      MYSQL_HOST: weight_db1
    ports:
      - "3306:3306"
    volumes:
      - ../../prod_env/main/weight/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - ../../prod_env/main/weight/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:



# billing-app:
#     image: python:3.12-slim
#     container_name: billing-app
#     working_dir: /app
#     volumes:
#       - ../prod_env/billing/flask-in:/app
#     command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_ENV=development
#       - MYSQL_HOST=billdb
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#       - MYSQL_DATABASE=billdb
#     ports:
#       - "8083:5500"
#     depends_on:
#       - billdb
#     networks:
#     - mynet

# billdb:
#     image: mysql:5.7
#     container_name: billdb
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: billdb
#     ports:
#       -3307:3306
#     volumes:
#       - ../../prod_env/billing/billdb:/docker-entrypoint-initdb.d
#     networks:
#       - mynet

networks:
  weight-network:
    external: true
